/**
 * Regenerates the committed, reviewed-bytes artifact for the F-001 portal fork
 * (`packages/bridge-evm/upstream/NuloTokenPortal.build.json`).
 *
 * The fork's body uses the REAL `@aztec` Solidity interfaces, so it only compiles inside the
 * l1-contracts root that `@aztec/l1-artifacts` ships (our own foundry project sees only a
 * minimal-interface shim). This stages the vendored fork into that root, builds it with the pinned
 * toolchain, asserts the bytes against the reviewed pins, and writes a trimmed artifact carrying the
 * bytes the live deploy will use plus the integrity pins.
 *
 * Why a COMMITTED artifact and not pure build-at-deploy: a one-shot irreversible cutover wants
 * "exact reviewed bytes", not "whatever builds today". `portal-artifact.ts` loads these bytes and
 * asserts them against the pins; the deploy ADDITIONALLY rebuilds-and-compares as a drift alarm.
 * Bumping the fork/toolchain is a deliberate event - regenerate here, review, then update the pins.
 *
 * Run from packages/bridge-core: `bun run scripts/build-portal-artifact.ts`.
 */
import { writeFileSync } from "node:fs"
import { assertPortalPins, buildForkInL1Root, FORKED_PORTAL_KECCAK, PORTAL_BUILD_JSON } from "./portal-artifact"

const built = buildForkInL1Root()
assertPortalPins(built)

writeFileSync(
	PORTAL_BUILD_JSON,
	`${JSON.stringify(
		{
			_note: "GENERATED by scripts/build-portal-artifact.ts - reviewed-bytes artifact for the F-001 portal fork. Do not hand-edit.",
			contractName: "NuloTokenPortal",
			source: "packages/bridge-evm/upstream/NuloTokenPortal.sol",
			sourceKeccak: FORKED_PORTAL_KECCAK,
			solcVersion: built.solcVersion,
			initCodeHash: built.initCodeHash,
			runtimeCodeHash: built.runtimeCodeHash,
			abi: built.abi,
			bytecode: built.bytecode,
			deployedBytecode: built.deployedBytecode,
		},
		null,
		"\t",
	)}\n`,
)
console.log(`wrote ${PORTAL_BUILD_JSON}`)
console.log(`  solc=${built.solcVersion} initCodeHash=${built.initCodeHash} runtimeCodeHash=${built.runtimeCodeHash}`)
