/**
 * Integrity pins + build/load helpers for the F-001 portal fork (`NuloTokenPortal`).
 *
 * The fork compiles ONLY inside the l1-contracts root that `@aztec/l1-artifacts` ships (its body
 * uses the real `@aztec` Solidity interfaces). The live deploy uses the COMMITTED reviewed bytes
 * (`upstream/NuloTokenPortal.build.json`, regenerated by `build-portal-artifact.ts`) so a one-shot
 * irreversible cutover deploys exact-reviewed bytes, not "whatever builds today". These pins are the
 * trust anchor: the committed artifact is asserted against them on load, and the deploy ADDITIONALLY
 * rebuilds-and-compares as a drift alarm. Bumping the fork or toolchain is a deliberate event -
 * regenerate the artifact, review the new bytes, then update these constants.
 *
 * Toolchain pin: forge 1.4.1 + solc 0.8.30 (l1-contracts foundry.toml: optimizer=true,
 * evm_version=prague). Captured from a clean build of upstream/NuloTokenPortal.sol.
 */
import { spawnSync } from "node:child_process"
import { copyFileSync, existsSync, mkdirSync, readFileSync } from "node:fs"
import { createRequire } from "node:module"
import { homedir } from "node:os"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { keccak256 } from "viem"

/** keccak256 of upstream/NuloTokenPortal.sol (the reviewed fork source). Re-pinned for the
 *  F-001 hardening: the fork gained a deployer-only initializer guard (constructor-pinned
 *  immutable) on top of the init-once guard — closes the front-run of the FIRST initialize
 *  (deploy and initialize are separate transactions). Diff reviewed: guard + error + header
 *  comments only; deposit/withdraw bodies untouched. */
export const FORKED_PORTAL_KECCAK = "0xde14278d6026459eec7461d12dd7d3bc57ff56d77cfee4b74a1ad2cc2d4d50ec"

/** Creation/runtime code hashes + solc version of the reviewed fork build. Regenerated twice for
 *  F-001 hardening: once for the deployer-only initializer guard, again after correcting the
 *  header's circularity wording — solc's metadata hash covers the source, so even comment-only
 *  edits change bytecode. Diff reviewed both times: comments/guard only, deposit/withdraw bodies
 *  untouched. The candidate smoke's deposit→claim round-trip is the empirical proof of the portal
 *  semantics post-guard. */
export const PORTAL_PIN = {
	solc: "0.8.30",
	initCodeHash: "0x4dfc96fc7f7de5e2aa5ca7de846ea6752f701b614ce0928e74e3c92522d8d7c1",
	runtimeCodeHash: "0x580419318282b189e24afbdf32177d54a4579b19aba885cce664613c00bb8652",
} as const

const here = dirname(fileURLToPath(import.meta.url))
const EVM_ROOT = join(here, "..", "..", "..", "contracts", "bridge", "evm")
export const VENDORED_FORK = join(EVM_ROOT, "upstream", "NuloTokenPortal.sol")
export const PORTAL_BUILD_JSON = join(EVM_ROOT, "upstream", "NuloTokenPortal.build.json")
const STAGE_REL = join("test", "portals", "NuloTokenPortal.sol")

export function forgeBin(): string {
	if (process.env.FORGE_BIN) return process.env.FORGE_BIN
	if (spawnSync("forge", ["--version"], { stdio: "ignore" }).status === 0) return "forge"
	const aztec = join(homedir(), ".aztec", "current", "bin", "forge")
	if (existsSync(aztec)) return aztec
	throw new Error("forge not found - install foundry or set FORGE_BIN.")
}

export function l1ContractsRoot(): string {
	return join(dirname(createRequire(import.meta.url).resolve("@aztec/l1-artifacts/package.json")), "l1-contracts")
}

/** Assert the vendored fork still hashes to the pin, then stage it into the l1-contracts root. */
export function stageForkSource(l1Root: string): string {
	const got = keccak256(readFileSync(VENDORED_FORK))
	if (got !== FORKED_PORTAL_KECCAK) {
		throw new Error(
			`fork source keccak ${got} != pinned ${FORKED_PORTAL_KECCAK} - the fork changed; review the diff, ` +
				"then regenerate the artifact and update FORKED_PORTAL_KECCAK.",
		)
	}
	const dest = join(l1Root, STAGE_REL)
	mkdirSync(dirname(dest), { recursive: true })
	copyFileSync(VENDORED_FORK, dest)
	return dest
}

export interface BuiltPortal {
	abi: unknown[]
	bytecode: `0x${string}`
	deployedBytecode: `0x${string}`
	solcVersion: string
	initCodeHash: `0x${string}`
	runtimeCodeHash: `0x${string}`
	immutableReferences: ReadonlyArray<{ start: number; length: number }>
}

/** Stage + `forge build` the fork in the l1-contracts root; returns its bytes + hashes. */
export function buildForkInL1Root(): BuiltPortal {
	const l1Root = l1ContractsRoot()
	stageForkSource(l1Root)
	const { FOUNDRY_PROFILE: _omit, ...env } = process.env
	const res = spawnSync(forgeBin(), ["build", STAGE_REL, "--use", PORTAL_PIN.solc], {
		cwd: l1Root,
		env,
		encoding: "utf8",
		maxBuffer: 64 * 1024 * 1024,
	})
	if (res.status !== 0) throw new Error(`forge build failed:\n${res.stdout ?? ""}${res.stderr ?? ""}`)
	const a = JSON.parse(readFileSync(join(l1Root, "out", "NuloTokenPortal.sol", "NuloTokenPortal.json"), "utf8"))
	const bytecode = a.bytecode.object as `0x${string}`
	const deployedBytecode = a.deployedBytecode.object as `0x${string}`
	const meta = typeof a.metadata === "string" ? JSON.parse(a.metadata) : a.metadata
	return {
		abi: a.abi,
		bytecode,
		deployedBytecode,
		solcVersion: meta?.compiler?.version as string,
		initCodeHash: keccak256(bytecode),
		runtimeCodeHash: keccak256(deployedBytecode),
		immutableReferences: Object.values(a.deployedBytecode.immutableReferences ?? {}).flat() as ReadonlyArray<{
			start: number
			length: number
		}>,
	}
}

/** Throw unless the built bytes match the reviewed pins. */
export function assertPortalPins(b: { initCodeHash: string; runtimeCodeHash: string; solcVersion: string }): void {
	const drift = [
		b.initCodeHash !== PORTAL_PIN.initCodeHash && `initCodeHash ${b.initCodeHash} != ${PORTAL_PIN.initCodeHash}`,
		b.runtimeCodeHash !== PORTAL_PIN.runtimeCodeHash && `runtimeCodeHash ${b.runtimeCodeHash} != ${PORTAL_PIN.runtimeCodeHash}`,
		!b.solcVersion?.startsWith(PORTAL_PIN.solc) && `solc ${b.solcVersion} != ${PORTAL_PIN.solc}`,
	].filter(Boolean)
	if (drift.length) throw new Error(`portal build drifted from the reviewed pins:\n  ${drift.join("\n  ")}`)
}

export interface LoadedPortal {
	abi: unknown[]
	bytecode: `0x${string}`
	runtimeCodeHash: `0x${string}`
	deployedBytecode: `0x${string}`
	immutableReferences: ReadonlyArray<{ start: number; length: number }>
}

/**
 * Load the committed reviewed-bytes artifact, asserting it against the pins AND against the current
 * fork source. This is the deploy's source of bytes - exact reviewed bytes, no rebuild required.
 */
export function loadForkedPortalArtifact(): LoadedPortal {
	if (!existsSync(PORTAL_BUILD_JSON)) {
		throw new Error(`${PORTAL_BUILD_JSON} missing - run \`bun run scripts/build-portal-artifact.ts\`.`)
	}
	const a = JSON.parse(readFileSync(PORTAL_BUILD_JSON, "utf8"))
	const srcKeccak = keccak256(readFileSync(VENDORED_FORK))
	if (a.sourceKeccak !== FORKED_PORTAL_KECCAK || srcKeccak !== FORKED_PORTAL_KECCAK) {
		throw new Error(
			`committed portal artifact source mismatch (artifact ${a.sourceKeccak}, source ${srcKeccak}, pin ` +
				`${FORKED_PORTAL_KECCAK}) - regenerate the artifact from the current fork.`,
		)
	}
	assertPortalPins({ initCodeHash: a.initCodeHash, runtimeCodeHash: a.runtimeCodeHash, solcVersion: a.solcVersion })
	return {
		abi: a.abi,
		bytecode: a.bytecode,
		deployedBytecode: a.deployedBytecode,
		runtimeCodeHash: a.runtimeCodeHash,
		immutableReferences: a.immutableReferences,
	}
}

/**
 * Throws when a rebuild moves or resizes an immutable site relative to the committed artifact.
 * Split out of `rebuildAndVerifyPortal` so it is reachable without a solc invocation — the
 * caller needs a real build, which is why this branch had no coverage.
 */
export function assertImmutableRefsMatch(
	rebuilt: ReadonlyArray<{ start: number; length: number }>,
	committed: ReadonlyArray<{ start: number; length: number }>,
): void {
	if (JSON.stringify(rebuilt) !== JSON.stringify(committed)) {
		throw new Error(`immutableReferences drifted: rebuilt ${JSON.stringify(rebuilt)} != committed ${JSON.stringify(committed)}`)
	}
}

/** Deploy-time drift alarm: rebuild from source and assert bytes AND immutable sites match pins. */
export function rebuildAndVerifyPortal(committedRefs?: ReadonlyArray<{ start: number; length: number }>): void {
	const built = buildForkInL1Root()
	assertPortalPins(built)
	if (committedRefs) assertImmutableRefsMatch(built.immutableReferences, committedRefs)
}

/**
 * Verify on-chain runtime code against the artifact TEMPLATE, accounting for immutables: the
 * constructor patches `initializer` into the deployed bytecode at the artifact's declared
 * immutableReferences, so raw keccak equality against the template can never hold. Reconstructs
 * the template by restoring every immutable site to its template bytes and requires byte-equality
 * with the real code; each site must encode exactly `expectedInitializer` (right-aligned in its
 * slot, leading zeros per solc address-immutable encoding). Returns the initializer DECODED from
 * the deployed bytes, so a caller comparing it against the broadcaster is making a real check.
 */
export function assertRuntimeMatchesTemplate(
	actualHex: `0x${string}`,
	templateHex: `0x${string}`,
	expectedInitializer: `0x${string}`,
	immutableReferences: ReadonlyArray<{ start: number; length: number }>,
): `0x${string}` {
	const toBytes = (h: string) => Uint8Array.from(Buffer.from(h.replace(/^0x/, ""), "hex"))
	const actual = toBytes(actualHex)
	const template = toBytes(templateHex)
	const expectedAddr = toBytes(expectedInitializer)
	if (actual.length !== template.length) {
		throw new Error(`runtime code length ${actual.length} != artifact template ${template.length}`)
	}
	for (const { start, length } of immutableReferences) {
		if (length < expectedAddr.length || start + length > actual.length) {
			throw new Error(`immutable reference [${start},${length}] out of bounds or too short for an address`)
		}
		const got = actual.subarray(start, start + length)
		const zeros = got.subarray(0, length - expectedAddr.length)
		const tail = got.subarray(length - expectedAddr.length)
		if (!zeros.every((b) => b === 0) || !tail.every((b, i) => b === expectedAddr[i])) {
			throw new Error(`immutable at ${start} does not encode the expected initializer (got 0x${Buffer.from(got).toString("hex")})`)
		}
	}
	const inPatch = (i: number) => immutableReferences.some(({ start, length }) => i >= start && i < start + length)
	for (let i = 0; i < actual.length; i++) {
		if (!inPatch(i) && actual[i] !== template[i]) {
			throw new Error(
				`non-immutable runtime drift at byte ${i} (got 0x${actual[i].toString(16)}, want 0x${template[i].toString(16)})`,
			)
		}
	}
	if (immutableReferences.length === 0) {
		throw new Error("artifact declares no immutable references — cannot verify the pinned initializer")
	}
	// Decoded from the deployed bytes rather than echoing the caller's argument: returning the
	// input made every caller-side comparison against it true by construction, which reads like
	// a second independent check and is not one.
	const first = immutableReferences[0]
	const decoded = `0x${Buffer.from(
		actual.subarray(first.start + first.length - expectedAddr.length, first.start + first.length),
	).toString("hex")}` as `0x${string}`
	return decoded
}
