/**
 * Integrity pins + build/load helpers for the F-001 portal fork (`NuloTokenPortal`).
 *
 * The fork compiles ONLY inside the l1-contracts root that `@aztec/l1-artifacts` ships (its body
 * uses the real `@aztec` Solidity interfaces). The live deploy uses the COMMITTED reviewed bytes
 * (`upstream/NuloTokenPortal.build.json`, regenerated by `build-portal-artifact.ts`) so a one-shot
 * irreversible cutover deploys exact-reviewed bytes, not "whatever builds today". These pins are the
 * trust anchor: the committed artifact is asserted against them on load, and the deploy ADDITIONALLY
 * rebuilds-and-compares as a drift alarm. Bumping the fork or toolchain is a deliberate event -
 * regenerate the artifact, review the new bytes, then update these constants.
 *
 * Toolchain pin: forge 1.4.1 + solc 0.8.30 (l1-contracts foundry.toml: optimizer=true,
 * evm_version=prague). Captured from a clean build of upstream/NuloTokenPortal.sol.
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync } from "node:fs"
import { createRequire } from "node:module"
import { homedir } from "node:os"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { keccak256 } from "viem"
import { resolveBin, run } from "./run"

/** keccak256 of upstream/NuloTokenPortal.sol (the reviewed fork source). Re-pinned for the
 *  F-001 hardening: the fork gained a deployer-only initializer guard (constructor-pinned
 *  immutable) on top of the init-once guard — closes the front-run of the FIRST initialize
 *  (deploy and initialize are separate transactions). Diff reviewed: guard + error + header
 *  comments only; deposit/withdraw bodies untouched. */
export const FORKED_PORTAL_KECCAK = "0x5e81eaad47a3ccf2827635d0dc19c7abb218926112594009e56cd104b2bbdd95"

/** Creation/runtime code hashes + solc version of the reviewed fork build. Regenerated for the
 *  F-001 hardening (deployer-only initializer guard added to the init-once guard; same 0.8.30
 *  l1-contracts toolchain). The candidate smoke's deposit→claim round-trip is the empirical proof
 *  of the portal semantics post-guard. */
export const PORTAL_PIN = {
	solc: "0.8.30",
	initCodeHash: "0x5cd282db90ecdc2f8ed3992a0c36f22eb69e9f98ad262bd8abb06a25476411e1",
	runtimeCodeHash: "0x7c7606cda9c2c7907a1abe2827b2c799fea571fa4edc3d11b07a4eaaf069b5d2",
} as const

const here = dirname(fileURLToPath(import.meta.url))
const EVM_ROOT = join(here, "..", "..", "..", "contracts", "bridge", "evm")
export const VENDORED_FORK = join(EVM_ROOT, "upstream", "NuloTokenPortal.sol")
export const PORTAL_BUILD_JSON = join(EVM_ROOT, "upstream", "NuloTokenPortal.build.json")
const STAGE_REL = join("test", "portals", "NuloTokenPortal.sol")

let forge: string | undefined

/** `FORGE_BIN` → PATH → the Aztec-bundled forge; resolved on first use, never at import. */
export function forgeBin(): string {
	forge ??= resolveBin("forge", {
		envVar: "FORGE_BIN",
		candidates: [join(homedir(), ".aztec", "current", "bin", "forge")],
		prefer: "path",
	})
	return forge
}

export function l1ContractsRoot(): string {
	return join(dirname(createRequire(import.meta.url).resolve("@aztec/l1-artifacts/package.json")), "l1-contracts")
}

/** Assert the vendored fork still hashes to the pin, then stage it into the l1-contracts root. */
export function stageForkSource(l1Root: string): string {
	const got = keccak256(readFileSync(VENDORED_FORK))
	if (got !== FORKED_PORTAL_KECCAK) {
		throw new Error(
			`fork source keccak ${got} != pinned ${FORKED_PORTAL_KECCAK} - the fork changed; review the diff, ` +
				"then regenerate the artifact and update FORKED_PORTAL_KECCAK.",
		)
	}
	const dest = join(l1Root, STAGE_REL)
	mkdirSync(dirname(dest), { recursive: true })
	copyFileSync(VENDORED_FORK, dest)
	return dest
}

export interface BuiltPortal {
	abi: unknown[]
	bytecode: `0x${string}`
	deployedBytecode: `0x${string}`
	solcVersion: string
	initCodeHash: `0x${string}`
	runtimeCodeHash: `0x${string}`
}

/** Stage + `forge build` the fork in the l1-contracts root; returns its bytes + hashes. */
export function buildForkInL1Root(): BuiltPortal {
	const l1Root = l1ContractsRoot()
	stageForkSource(l1Root)
	const { FOUNDRY_PROFILE: _omit, ...env } = process.env
	const res = run(forgeBin(), ["build", STAGE_REL, "--use", PORTAL_PIN.solc], {
		cwd: l1Root,
		env,
		maxBuffer: 64 * 1024 * 1024,
		check: false,
	})
	if (res.exitCode !== 0) throw new Error(`forge build failed:\n${res.stdout}${res.stderr}`)
	const a = JSON.parse(readFileSync(join(l1Root, "out", "NuloTokenPortal.sol", "NuloTokenPortal.json"), "utf8"))
	const bytecode = a.bytecode.object as `0x${string}`
	const deployedBytecode = a.deployedBytecode.object as `0x${string}`
	const meta = typeof a.metadata === "string" ? JSON.parse(a.metadata) : a.metadata
	return {
		abi: a.abi,
		bytecode,
		deployedBytecode,
		solcVersion: meta?.compiler?.version as string,
		initCodeHash: keccak256(bytecode),
		runtimeCodeHash: keccak256(deployedBytecode),
	}
}

/** Throw unless the built bytes match the reviewed pins. */
export function assertPortalPins(b: { initCodeHash: string; runtimeCodeHash: string; solcVersion: string }): void {
	const drift = [
		b.initCodeHash !== PORTAL_PIN.initCodeHash && `initCodeHash ${b.initCodeHash} != ${PORTAL_PIN.initCodeHash}`,
		b.runtimeCodeHash !== PORTAL_PIN.runtimeCodeHash && `runtimeCodeHash ${b.runtimeCodeHash} != ${PORTAL_PIN.runtimeCodeHash}`,
		!b.solcVersion?.startsWith(PORTAL_PIN.solc) && `solc ${b.solcVersion} != ${PORTAL_PIN.solc}`,
	].filter(Boolean)
	if (drift.length) throw new Error(`portal build drifted from the reviewed pins:\n  ${drift.join("\n  ")}`)
}

export interface LoadedPortal {
	abi: unknown[]
	bytecode: `0x${string}`
	runtimeCodeHash: `0x${string}`
}

/**
 * Load the committed reviewed-bytes artifact, asserting it against the pins AND against the current
 * fork source. This is the deploy's source of bytes - exact reviewed bytes, no rebuild required.
 */
export function loadForkedPortalArtifact(): LoadedPortal {
	if (!existsSync(PORTAL_BUILD_JSON)) {
		throw new Error(`${PORTAL_BUILD_JSON} missing - run \`bun run scripts/build-portal-artifact.ts\`.`)
	}
	const a = JSON.parse(readFileSync(PORTAL_BUILD_JSON, "utf8"))
	const srcKeccak = keccak256(readFileSync(VENDORED_FORK))
	if (a.sourceKeccak !== FORKED_PORTAL_KECCAK || srcKeccak !== FORKED_PORTAL_KECCAK) {
		throw new Error(
			`committed portal artifact source mismatch (artifact ${a.sourceKeccak}, source ${srcKeccak}, pin ` +
				`${FORKED_PORTAL_KECCAK}) - regenerate the artifact from the current fork.`,
		)
	}
	assertPortalPins({ initCodeHash: a.initCodeHash, runtimeCodeHash: a.runtimeCodeHash, solcVersion: a.solcVersion })
	return { abi: a.abi, bytecode: a.bytecode, runtimeCodeHash: a.runtimeCodeHash }
}

/** Deploy-time drift alarm: rebuild from source and assert the bytes still match the pins. */
export function rebuildAndVerifyPortal(): void {
	assertPortalPins(buildForkInL1Root())
}
