/**
 * Integrity pins + build/load helpers for the F-001 portal fork (`NuloTokenPortal`).
 *
 * The fork compiles ONLY inside the l1-contracts root that `@aztec/l1-artifacts` ships (its body
 * uses the real `@aztec` Solidity interfaces). The live deploy uses the COMMITTED reviewed bytes
 * (`upstream/NuloTokenPortal.build.json`, regenerated by `build-portal-artifact.ts`) so a one-shot
 * irreversible cutover deploys exact-reviewed bytes, not "whatever builds today". These pins are the
 * trust anchor: the committed artifact is asserted against them on load, and the deploy ADDITIONALLY
 * rebuilds-and-compares as a drift alarm. Bumping the fork or toolchain is a deliberate event -
 * regenerate the artifact, review the new bytes, then update these constants.
 *
 * Toolchain pin: forge 1.4.1 + solc 0.8.30 (l1-contracts foundry.toml: optimizer=true,
 * evm_version=prague). Captured from a clean build of upstream/NuloTokenPortal.sol.
 */
import { spawnSync } from "node:child_process"
import { copyFileSync, existsSync, mkdirSync, readFileSync } from "node:fs"
import { createRequire } from "node:module"
import { homedir } from "node:os"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { keccak256 } from "viem"

/** keccak256 of upstream/NuloTokenPortal.sol (the reviewed fork source). Re-pinned after the
 *  monorepo restructure repathed ONE header-comment line inside the fork
 *  (`packages/bridge-evm/…` → `contracts/bridge/evm/…`) without regenerating this pin —
 *  diff reviewed: comment-only, zero code change. */
export const FORKED_PORTAL_KECCAK = "0x1820c1ab1da9ffcd9e443350639e803a8019f624a8e967bc2dd86e8ec21f96b8"

/** Creation/runtime code hashes + solc version of the reviewed fork build. Regenerated for the
 *  5.0.0-rc.2 l1-contracts toolchain (the fork's `@aztec` interface imports now resolve against
 *  rc.2; the fork source itself is unchanged beyond the repathed header comment). The candidate
 *  smoke's deposit→claim round-trip is the empirical proof of the rc.2 portal semantics.
 *  Re-validated live on the 5.0.0 network (Etherscan-verified + candidate smoke) without a
 *  recompile — the artifact provenance stays the rc.2 toolchain deliberately. */
export const PORTAL_PIN = {
	solc: "0.8.30",
	initCodeHash: "0x7886020a18cdd8d5b6dea0bfb94e2edbdf7d5e4927094f3a17b7022840b4d26e",
	runtimeCodeHash: "0x851a507b53399339973c204767e4bddbaae2ecf4499cb4df1f40a54cd3963ca6",
} as const

const here = dirname(fileURLToPath(import.meta.url))
const EVM_ROOT = join(here, "..", "..", "..", "contracts", "bridge", "evm")
export const VENDORED_FORK = join(EVM_ROOT, "upstream", "NuloTokenPortal.sol")
export const PORTAL_BUILD_JSON = join(EVM_ROOT, "upstream", "NuloTokenPortal.build.json")
const STAGE_REL = join("test", "portals", "NuloTokenPortal.sol")

export function forgeBin(): string {
	if (process.env.FORGE_BIN) return process.env.FORGE_BIN
	if (spawnSync("forge", ["--version"], { stdio: "ignore" }).status === 0) return "forge"
	const aztec = join(homedir(), ".aztec", "current", "bin", "forge")
	if (existsSync(aztec)) return aztec
	throw new Error("forge not found - install foundry or set FORGE_BIN.")
}

export function l1ContractsRoot(): string {
	return join(dirname(createRequire(import.meta.url).resolve("@aztec/l1-artifacts/package.json")), "l1-contracts")
}

/** Assert the vendored fork still hashes to the pin, then stage it into the l1-contracts root. */
export function stageForkSource(l1Root: string): string {
	const got = keccak256(readFileSync(VENDORED_FORK))
	if (got !== FORKED_PORTAL_KECCAK) {
		throw new Error(
			`fork source keccak ${got} != pinned ${FORKED_PORTAL_KECCAK} - the fork changed; review the diff, ` +
				"then regenerate the artifact and update FORKED_PORTAL_KECCAK.",
		)
	}
	const dest = join(l1Root, STAGE_REL)
	mkdirSync(dirname(dest), { recursive: true })
	copyFileSync(VENDORED_FORK, dest)
	return dest
}

export interface BuiltPortal {
	abi: unknown[]
	bytecode: `0x${string}`
	deployedBytecode: `0x${string}`
	solcVersion: string
	initCodeHash: `0x${string}`
	runtimeCodeHash: `0x${string}`
}

/** Stage + `forge build` the fork in the l1-contracts root; returns its bytes + hashes. */
export function buildForkInL1Root(): BuiltPortal {
	const l1Root = l1ContractsRoot()
	stageForkSource(l1Root)
	const { FOUNDRY_PROFILE: _omit, ...env } = process.env
	const res = spawnSync(forgeBin(), ["build", STAGE_REL, "--use", PORTAL_PIN.solc], {
		cwd: l1Root,
		env,
		encoding: "utf8",
		maxBuffer: 64 * 1024 * 1024,
	})
	if (res.status !== 0) throw new Error(`forge build failed:\n${res.stdout ?? ""}${res.stderr ?? ""}`)
	const a = JSON.parse(readFileSync(join(l1Root, "out", "NuloTokenPortal.sol", "NuloTokenPortal.json"), "utf8"))
	const bytecode = a.bytecode.object as `0x${string}`
	const deployedBytecode = a.deployedBytecode.object as `0x${string}`
	const meta = typeof a.metadata === "string" ? JSON.parse(a.metadata) : a.metadata
	return {
		abi: a.abi,
		bytecode,
		deployedBytecode,
		solcVersion: meta?.compiler?.version as string,
		initCodeHash: keccak256(bytecode),
		runtimeCodeHash: keccak256(deployedBytecode),
	}
}

/** Throw unless the built bytes match the reviewed pins. */
export function assertPortalPins(b: { initCodeHash: string; runtimeCodeHash: string; solcVersion: string }): void {
	const drift = [
		b.initCodeHash !== PORTAL_PIN.initCodeHash && `initCodeHash ${b.initCodeHash} != ${PORTAL_PIN.initCodeHash}`,
		b.runtimeCodeHash !== PORTAL_PIN.runtimeCodeHash && `runtimeCodeHash ${b.runtimeCodeHash} != ${PORTAL_PIN.runtimeCodeHash}`,
		!b.solcVersion?.startsWith(PORTAL_PIN.solc) && `solc ${b.solcVersion} != ${PORTAL_PIN.solc}`,
	].filter(Boolean)
	if (drift.length) throw new Error(`portal build drifted from the reviewed pins:\n  ${drift.join("\n  ")}`)
}

export interface LoadedPortal {
	abi: unknown[]
	bytecode: `0x${string}`
	runtimeCodeHash: `0x${string}`
}

/**
 * Load the committed reviewed-bytes artifact, asserting it against the pins AND against the current
 * fork source. This is the deploy's source of bytes - exact reviewed bytes, no rebuild required.
 */
export function loadForkedPortalArtifact(): LoadedPortal {
	if (!existsSync(PORTAL_BUILD_JSON)) {
		throw new Error(`${PORTAL_BUILD_JSON} missing - run \`bun run scripts/build-portal-artifact.ts\`.`)
	}
	const a = JSON.parse(readFileSync(PORTAL_BUILD_JSON, "utf8"))
	const srcKeccak = keccak256(readFileSync(VENDORED_FORK))
	if (a.sourceKeccak !== FORKED_PORTAL_KECCAK || srcKeccak !== FORKED_PORTAL_KECCAK) {
		throw new Error(
			`committed portal artifact source mismatch (artifact ${a.sourceKeccak}, source ${srcKeccak}, pin ` +
				`${FORKED_PORTAL_KECCAK}) - regenerate the artifact from the current fork.`,
		)
	}
	assertPortalPins({ initCodeHash: a.initCodeHash, runtimeCodeHash: a.runtimeCodeHash, solcVersion: a.solcVersion })
	return { abi: a.abi, bytecode: a.bytecode, runtimeCodeHash: a.runtimeCodeHash }
}

/** Deploy-time drift alarm: rebuild from source and assert the bytes still match the pins. */
export function rebuildAndVerifyPortal(): void {
	assertPortalPins(buildForkInL1Root())
}
