<script setup>
/**
 * Renders the recovery-phrase input plus the new+confirm password section.
 * The visibility toggles for both the secret field and the password field
 * are local state.
 *
 * Section labels carry the visual heading; individual Inputs run
 * label-less to avoid duplicating the heading text. Hints (strength,
 * "Correct" indicator) move under each input via the #bottom slot so
 * they share the same below-input rail the error rail uses.
 */
const props = defineProps({
	method: { type: String, required: true }, // 'seed'
	error: { type: Object, default: () => ({ type: "", title: "", tooltip: "" }) },
	maxPasswordLength: { type: Number, default: 128 },
})

const emit = defineEmits(["secretInput", "passwordInput"])

const seedPhrase = defineModel("seedPhrase", { default: undefined })
const password = defineModel("password", { default: "" })
const repeatedPassword = defineModel("repeatedPassword", { default: "" })

const isPasswordType = ref(true)
const hideCredentials = ref(true)

const passwordHint = computed(() => {
	if (!password.value || password.value?.length < 8) return "At least 8 characters"
	if (password.value !== repeatedPassword.value) return "Passwords don't match"
	if (password.value?.length > 24) return "Long enough. Don't forget it."
	return "Strong password"
})
</script>

<template>
	<div :class="$style.section">
		<Flex align="center" gap="6">
			<span :class="$style.section_label">Recovery Phrase</span>
			<Tooltip position="start">
				<Icon name="info" size="11" color="tertiary" hoverColor="primary" />
				<template #content>24 words separated by spaces. Use a phrase generated by Nulo — a phrase shared with another wallet lets that software derive your keys.</template>
			</Tooltip>
		</Flex>

		<Input
			v-if="method === 'seed'"
			v-model="seedPhrase"
			data-testid="import-seed-input"
			@input="emit('secretInput')"
			:type="hideCredentials ? 'password' : 'text'"
			placeholder="Enter recovery phrase"
		>
			<template #suffix>
				<button
					type="button"
					@click="hideCredentials = !hideCredentials"
					tabindex="-1" :class="$style.visibility_btn"
					:aria-label="hideCredentials ? 'Show recovery phrase' : 'Hide recovery phrase'"
				>
					<MaterialIcon
						:name="hideCredentials ? 'visibility' : 'visibility_off'"
						:size="18"
						color="secondary"
					/>
				</button>
			</template>
			<template v-if="seedPhrase?.split(' ').length === 24" #bottom>
				<Flex align="center" gap="4" :class="$style.hint_row">
					<Icon name="check-circle" size="12" color="green" />
					<Text size="12" weight="600" color="primary">Correct</Text>
				</Flex>
			</template>
		</Input>
	</div>

	<div :class="$style.section_last">
		<span :class="$style.section_label">New Password</span>
		<Flex direction="column" gap="12">
			<Input
				v-model="password"
				data-testid="import-password-input"
				:type="isPasswordType ? 'password' : 'text'"
				@input="emit('passwordInput')"
				:maxLength="maxPasswordLength"
				placeholder="Enter new password"
			>
				<template #suffix>
					<button
						type="button"
						@click="isPasswordType = !isPasswordType"
						tabindex="-1" :class="$style.visibility_btn"
						:aria-label="isPasswordType ? 'Show password' : 'Hide password'"
					>
						<MaterialIcon
							:name="isPasswordType ? 'visibility' : 'visibility_off'"
							:size="18"
							color="secondary"
						/>
					</button>
				</template>
				<template #bottom>
					<Flex align="center" gap="6" :class="$style.hint_row">
						<MaterialIcon name="lock" :size="12" color="tertiary" />
						<Text size="12" weight="600" color="tertiary">{{ passwordHint }}</Text>
					</Flex>
				</template>
			</Input>
			<Input
				v-model="repeatedPassword"
				data-testid="import-password-confirm-input"
				:type="isPasswordType ? 'password' : 'text'"
				@input="emit('passwordInput')"
				:maxLength="maxPasswordLength"
				placeholder="Repeat password"
			/>
		</Flex>

		<Flex v-if="error.type === 'unknown'" align="center" gap="8" :class="$style.unknown_error">
			<span :class="$style.error_tag">Error</span>
			<Text size="12" weight="600" color="secondary">{{ error.title }}</Text>
		</Flex>
	</div>
</template>

<style module>
/* No section-level border-bottom: each section's last child is an Input
 * whose `.base { border-bottom }` already underlines the section. The
 * extra divider produced two 1px lines stacked ~20px apart. */
.section {
	display: flex;
	flex-direction: column;
	gap: 12px;
	padding: 20px 0;
}

.section_last {
	display: flex;
	flex-direction: column;
	gap: 12px;
	padding: 20px 0;
}

.section_label {
	font-family: var(--font-headline);
	font-size: 11px;
	font-weight: 700;
	text-transform: uppercase;
	letter-spacing: 0.18em;
	color: var(--nulo-secondary);
}

.visibility_btn {
	display: flex;
	align-items: center;
	justify-content: center;
	background: transparent;
	border: none;
	cursor: pointer;
	padding: 4px 0 4px 8px;
}

/* Below-input hint rail (strength meter, "Correct" indicator). Subtle
 * left margin keeps the row visually anchored to the input below it,
 * separate from the input's content edge. */
.hint_row {
	margin-top: 4px;
}

.unknown_error {
	margin-top: 12px;
}

.error_tag {
	font-family: var(--font-headline);
	font-size: 10px;
	font-weight: 700;
	letter-spacing: 0.2em;
	text-transform: uppercase;
	color: var(--red);
	border: 1px solid var(--red);
	padding: 2px 6px;
	flex-shrink: 0;
}
</style>
