// The decided mocks, one entry per reference shot. `unfold` opens the earlier-round folds that hold them.
// Round-5 entries are the drawn recommendations; a different pick from the owner replaces its entry.
export const TARGETS = [
	{ name: "01-account-names", sel: '#i1-f1 [data-opt="A"]', unfold: ["i1-f1"] },
	{ name: "02-tooltip", sel: '#i2-f1 [data-opt="A"]', unfold: ["i2-f1"] },
	{ name: "03-fee-matrix", sel: "#fx3-grid", unfold: ["i3-f3"] },
	{ name: "03-fee-round1", sel: '#i3-f1 [data-opt="A"]', unfold: ["i3-f1"] },
	{ name: "03-menu-unknown-U14", sel: '#i3-r5 [data-opt="U14A"]' },
	{ name: "03-spoken-U15", sel: '#i3-r5 [data-opt="U15A"]' },
	{ name: "03-handadded-U16", sel: '#i3-r5 [data-opt="U16A"]' },
	{ name: "04-window-placement", sel: '#i4-f1 [data-opt="A"]', unfold: ["i4-f1"] },
	{ name: "05-onboarding", sel: '#i5-f1 [data-opt="A"]', unfold: ["i5-f1"] },
	{ name: "05-import-U11", sel: '#i5-r5 [data-opt="U11"]' },
	{ name: "06-auth-row-B", sel: '#i6-r4 [data-opt="WB"]', unfold: ["i6-f4"] },
	{ name: "06-window-S1", sel: '#i6-r4 [data-opt="S1B"]', unfold: ["i6-f4"] },
	{ name: "06-window-S2", sel: '#i6-f3 [data-opt="S2"]', unfold: ["i6-f3"] },
	{ name: "06-window-S3", sel: '#i6-f3 [data-opt="S3"]', unfold: ["i6-f3"] },
	{ name: "06-off-means-ask", sel: '#i6-f2 [data-opt="OFF1"]', unfold: ["i6-f2"] },
	{ name: "06-more-U1", sel: '#i6-r5 [data-opt="U1A"]' },
	{ name: "06-accounts-U2", sel: '#i6-r5 [data-opt="U2"]' },
	{ name: "06-banners-U3", sel: '#i6-r5 [data-opt="U3"]' },
	{ name: "06-rows-U4", sel: '#i6-r5 [data-opt="U4"]' },
	{ name: "06-row-list-U4", sel: "#i6-r5 .rowdict-wrap" },
	{ name: "06-rename-U5", sel: '#i6-r5 [data-opt="U5"]' },
	{ name: "06-auth-window-U6", sel: '#i6-r5 [data-opt="U6"]' },
	{ name: "06-settings-U7", sel: '#i6-r5 [data-opt="U7A"]' },
	{ name: "07-lock-chip", sel: '#i7-f2 [data-opt="A1"]', unfold: ["i7-f2"] },
	{ name: "08-privacy-strip", sel: '#i8-f1 [data-opt="B"]', unfold: ["i8-f1"] },
	{ name: "08-review-U12", sel: '#i8-r5 [data-opt="U12"]' },
	{ name: "08-unknown-U13", sel: '#i8-r5 [data-opt="U13A"]' },
	{ name: "09-home-dotted", sel: '#i9-f3 [data-opt="H3"]', unfold: ["i9-f3"] },
	{ name: "09-glossary", sel: '#i9-f3 [data-opt="G3"]', unfold: ["i9-f3"] },
	{ name: "09-definitions", sel: "#i9-f3 .facts", unfold: ["i9-f3"] },
	{ name: "09-claude-md-rule", sel: "#i9-f3 .clmd", unfold: ["i9-f3"] },
	{ name: "tips-icon-labels", sel: '#tips-f2 [data-opt="C"]', unfold: ["tips-f2"] },
	{ name: "tips-map", sel: "#tips-f2", unfold: ["tips-f2"] },
	{ name: "tips-host-U8", sel: '#tips-r5 [data-opt="U8"]' },
	{ name: "tips-phrase-U9", sel: '#tips-r5 [data-opt="U9"]' },
	{ name: "10-snackbar", sel: '#i10-f2 [data-opt="A1"]', unfold: ["i10-f2"] },
	{ name: "10-round1", sel: '#i10-f1 [data-opt="A"]', unfold: ["i10-f1"] },
	{ name: "11-rows", sel: '#i11-f1 [data-opt="A"]', unfold: ["i11-f1"] },
	{ name: "12-arrival", sel: '#i12-f2 [data-opt="A"]', unfold: ["i12-f2"] },
	{ name: "12-incoming", sel: '#i12-f2 [data-opt="B"]', unfold: ["i12-f2"] },
];
