// The decided mocks, one entry per reference shot. `unfold` opens the earlier-round folds that hold them.
export const TARGETS = [
	{ name: "01-account-names", sel: '#i1-f1 [data-opt="A"]', unfold: ["i1-f1"] },
	{ name: "02-tooltip", sel: '#i2-f1 [data-opt="A"]', unfold: ["i2-f1"] },
	{ name: "03-fee-matrix", sel: "#fx3-grid", unfold: ["i3-f3"] },
	{ name: "03-fee-round1", sel: '#i3-f1 [data-opt="A"]', unfold: ["i3-f1"] },
	{ name: "04-window-placement", sel: '#i4-f1 [data-opt="A"]', unfold: ["i4-f1"] },
	{ name: "05-onboarding", sel: '#i5-f1 [data-opt="A"]', unfold: ["i5-f1"] },
	{ name: "06-auth-row-B", sel: '#i6-r4 [data-opt="WB"]' },
	{ name: "06-window-S1", sel: '#i6-r4 [data-opt="S1B"]' },
	{ name: "06-window-S2", sel: '#i6-f3 [data-opt="S2"]', unfold: ["i6-f3"] },
	{ name: "06-window-S3", sel: '#i6-f3 [data-opt="S3"]', unfold: ["i6-f3"] },
	{ name: "06-off-means-ask", sel: '#i6-f2 [data-opt="OFF1"]', unfold: ["i6-f2"] },
	{ name: "07-lock-chip", sel: '#i7-f2 [data-opt="A1"]', unfold: ["i7-f2"] },
	{ name: "08-privacy-strip", sel: '#i8-f1 [data-opt="B"]', unfold: ["i8-f1"] },
	{ name: "09-home-dotted", sel: '#i9-f3 [data-opt="H3"]', unfold: ["i9-f3"] },
	{ name: "09-glossary", sel: '#i9-f3 [data-opt="G3"]', unfold: ["i9-f3"] },
	{ name: "09-definitions", sel: "#i9-f3 .facts", unfold: ["i9-f3"] },
	{ name: "09-claude-md-rule", sel: "#i9-f3 .clmd", unfold: ["i9-f3"] },
	{ name: "tips-icon-labels", sel: '#tips [data-opt="C"]' },
	{ name: "tips-map", sel: "#tips" },
	{ name: "10-snackbar", sel: '#i10-f2 [data-opt="A1"]', unfold: ["i10-f2"] },
	{ name: "10-round1", sel: '#i10-f1 [data-opt="A"]', unfold: ["i10-f1"] },
	{ name: "11-rows", sel: '#i11-f1 [data-opt="A"]', unfold: ["i11-f1"] },
	{ name: "12-arrival", sel: '#i12-f2 [data-opt="A"]', unfold: ["i12-f2"] },
	{ name: "12-incoming", sel: '#i12-f2 [data-opt="B"]', unfold: ["i12-f2"] },
];
