// The decided mocks, one entry per reference shot. `unfold` opens the earlier-round folds that hold them.
// Round-5 entries are the drawn recommendations; a different pick from the owner replaces its entry.
export const TARGETS = [
	{ name: "01-account-names", sel: '#i1-f1 [data-opt="A"]', unfold: ["i1-f1"] },
	{ name: "02-tooltip", sel: '#i2-f1 [data-opt="A"]', unfold: ["i2-f1"] },
	{ name: "03-fee-matrix", sel: "#fx3-grid", unfold: ["i3-f3"] },
	{ name: "03-fee-round1", sel: '#i3-f1 [data-opt="A"]', unfold: ["i3-f1"] },
	{ name: "03-menu-unknown-U14", sel: '#i3-r5 [data-opt="U14A"]' },
	{ name: "03-spoken-U15", sel: '#i3-r5 [data-opt="U15A"]' },
	{ name: "03-handadded-U16", sel: '#i3-r5 [data-opt="U16A"]' },
	{ name: "04-window-placement", sel: '#i4-f1 [data-opt="A"]', unfold: ["i4-f1"] },
	{ name: "05-onboarding", sel: '#i5-f1 [data-opt="A"]', unfold: ["i5-f1"] },
	{ name: "05-import-U11", sel: '#i5-r5 [data-opt="U11"]' },
	{ name: "06-auth-row-B", sel: '#i6-r4 [data-opt="WB"]', unfold: ["i6-f4"] },
	{ name: "06-window-S1", sel: '#i6-r4 [data-opt="S1B"]', unfold: ["i6-f4"] },
	{ name: "06-window-S2", sel: '#i6-f3 [data-opt="S2"]', unfold: ["i6-f3"] },
	{ name: "06-window-S3", sel: '#i6-f3 [data-opt="S3"]', unfold: ["i6-f3"] },
	{ name: "06-off-means-ask", sel: '#i6-f2 [data-opt="OFF1"]', unfold: ["i6-f2"] },
	{ name: "06-more-U1", sel: '#i6-r5 [data-opt="U1A"]' },
	{ name: "06-accounts-U2", sel: '#i6-r5 [data-opt="U2"]' },
	{ name: "06-banners-U3", sel: '#i6-r5 [data-opt="U3"]' },
	{ name: "06-rows-U4", sel: '#i6-r5 [data-opt="U4"]' },
	{ name: "06-row-list-U4", sel: "#i6-r5 .rowdict-wrap" },
	{ name: "06-rename-U5", sel: '#i6-r5 [data-opt="U5"]' },
	{ name: "06-auth-window-U6", sel: '#i6-r5 [data-opt="U6"]' },
	{ name: "06-settings-U7", sel: '#i6-r5 [data-opt="U7A"]' },
	// Round-5 addendum: one entry per drawn crop of each ask's recommended option.
	{ name: "06-interim-window-A1", sel: "#i6a1-window" },
	{ name: "06-interim-auth-off-A1", sel: "#i6a1-auth-off" },
	{ name: "06-interim-auth-broad-A1", sel: "#i6a1-auth-broad" },
	{ name: "06-interim-auth-broad-on-A1", sel: "#i6a1-auth-broad-on" },
	{ name: "06-interim-data-A1", sel: "#i6a1-data" },
	{ name: "06-interim-data-off-A1", sel: "#i6a1-data-off" },
	{ name: "06-interim-unknown-A1", sel: "#i6a1-unknown" },
	{ name: "06-interim-held-A1", sel: "#i6a1-held" },
	{ name: "06-no-scope-A2", sel: "#i6a2-rows" },
	{ name: "06-denied-A4", sel: "#i6a4-row" },
	{ name: "06-denied-data-A4", sel: "#i6a4-data" },
	{ name: "06-widen-any-A5", sel: "#i6a5-broad" },
	{ name: "06-widen-listed-A5", sel: "#i6a5-listed" },
	{ name: "06-flags-broad-A6", sel: "#i6a6-broad" },
	{ name: "06-flags-listed-A6", sel: "#i6a6-listed" },
	{ name: "06-details-any-A7", sel: "#i6a7-broad" },
	{ name: "06-details-mixed-A7", sel: "#i6a7-mixed" },
	{ name: "06-any-function-A8", sel: "#i6a8-fns" },
	{ name: "06-counts-A10", sel: "#i6a10-counts" },
	{ name: "06-fold-count-A10", sel: "#i6a10-fold" },
	{ name: "06-address-one-A11", sel: "#i6a11-one" },
	{ name: "06-address-renaming-A11", sel: "#i6a11-typing" },
	{ name: "06-address-two-A11", sel: "#i6a11-two" },
	{ name: "06-fold-open-A12", sel: "#i6a12-open" },
	{ name: "06-banner-more-A13", sel: "#i6a13-banner" },
	{ name: "06-chain-fallback-A14", sel: "#i6a14-id" },
	{ name: "06-chain-none-A14", sel: "#i6a14-none" },
	{ name: "06-chain-more-A14", sel: "#i6a14-more" },
	{ name: "06-settings-broad-A15", sel: "#i6a15-broad" },
	{ name: "06-settings-no-scope-A15", sel: "#i6a15-noscope" },
	{ name: "06-icons-A17", sel: "#i6a17-icons" },
	{ name: "06-dotted-count-A18", sel: "#i6a18-terms" },
	{ name: "06-copy-tab-A23", sel: '#i6-a23 [data-opt="A23"] .stage' },
	{ name: "06-utilities-any-A24", sel: "#i6a24-util" },
	{ name: "06-none-selected-A25", sel: "#i6a25-none" },
	{ name: "06-shared-row-A26", sel: "#i6a26-locked" },
	{ name: "06-spoken-rows-A27", sel: '#i6-a27 [data-opt="A27"] .stage' },
	{ name: "06-settings-error-A28", sel: "#i6a28-error" },
	{ name: "06-any-flag-A29", sel: "#i6a29-flag" },
	{ name: "06-declined-A30", sel: "#i6a30-window" },
	{ name: "06-declined-both-A30", sel: "#i6a30-both" },
	{ name: "06-declined-table-A30", sel: "#i6a30-tables" },
	{ name: "06-adding-A31", sel: "#i6a31-window" },
	{ name: "06-adding-interim-A31", sel: "#i6a31-interim" },
	{ name: "06-asked-again-A32", sel: "#i6a32-again" },
	{ name: "06-no-window-A32", sel: "#i6a32-none" },
	{ name: "07-lock-chip", sel: '#i7-f2 [data-opt="A1"]', unfold: ["i7-f2"] },
	{ name: "08-privacy-strip", sel: '#i8-f1 [data-opt="B"]', unfold: ["i8-f1"] },
	{ name: "08-review-U12", sel: '#i8-r5 [data-opt="U12"]' },
	{ name: "08-unknown-U13", sel: '#i8-r5 [data-opt="U13A"]' },
	{ name: "09-home-dotted", sel: '#i9-f3 [data-opt="H3"]', unfold: ["i9-f3"] },
	{ name: "09-glossary", sel: '#i9-f3 [data-opt="G3"]', unfold: ["i9-f3"] },
	{ name: "09-definitions", sel: "#i9-f3 .facts", unfold: ["i9-f3"] },
	{ name: "09-claude-md-rule", sel: "#i9-f3 .clmd", unfold: ["i9-f3"] },
	{ name: "tips-icon-labels", sel: '#tips-f2 [data-opt="C"]', unfold: ["tips-f2"] },
	{ name: "tips-map", sel: "#tips-f2", unfold: ["tips-f2"] },
	{ name: "tips-host-U8", sel: '#tips-r5 [data-opt="U8"]' },
	{ name: "tips-phrase-U9", sel: '#tips-r5 [data-opt="U9"]' },
	{ name: "10-snackbar", sel: '#i10-f2 [data-opt="A1"]', unfold: ["i10-f2"] },
	{ name: "10-round1", sel: '#i10-f1 [data-opt="A"]', unfold: ["i10-f1"] },
	{ name: "11-rows", sel: '#i11-f1 [data-opt="A"]', unfold: ["i11-f1"] },
	{ name: "12-arrival", sel: '#i12-f2 [data-opt="A"]', unfold: ["i12-f2"] },
	{ name: "12-incoming", sel: '#i12-f2 [data-opt="B"]', unfold: ["i12-f2"] },
];
