/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ACTIVITY_FEED_KINDS: typeof import('../utils/journal-state').ACTIVITY_FEED_KINDS
  const AccessLevel: typeof import('../utils/confirmation-policies').AccessLevel
  const CHAIN_IDS: typeof import('../utils/chain-ids').CHAIN_IDS
  const EffectScope: typeof import('vue').EffectScope
  const FEE_METHODS: typeof import('../utils/tx-enrichment').FEE_METHODS
  const IMPORT_ACTIVATION_TIMEOUT_MS: typeof import('../composables/completeImportWithRecovery').IMPORT_ACTIVATION_TIMEOUT_MS
  const MAINNET_L1_CHAIN_ID: typeof import('../utils/chain-ids').MAINNET_L1_CHAIN_ID
  const MAINNET_ROLLUP_VERSION: typeof import('../utils/chain-ids').MAINNET_ROLLUP_VERSION
  const MAX_CONTACT_IMPORT_BYTES: typeof import('../utils/contacts-export-format').MAX_CONTACT_IMPORT_BYTES
  const MAX_CONTACT_IMPORT_ROWS: typeof import('../utils/contacts-export-format').MAX_CONTACT_IMPORT_ROWS
  const THEME_HINT_KEY: typeof import('../utils/general').THEME_HINT_KEY
  const TOAST_DURATION: typeof import('../composables/toast.js').TOAST_DURATION
  const activateNetworkGuarded: typeof import('../utils/guarded-network-activation').activateNetworkGuarded
  const balanceFormatted: typeof import('../utils/amount').balanceFormatted
  const browser: typeof import('webextension-polyfill')
  const buildActivityRows: typeof import('../utils/activity-rows').buildActivityRows
  const buildFeeEstimate: typeof import('../utils/fee-estimation').buildFeeEstimate
  const buildJournalTerminalCardProps: typeof import('../utils/journal-state').buildJournalTerminalCardProps
  const capitalize: typeof import('../utils/string').capitalize
  const categoricalLabel: typeof import('../utils/journal-state').categoricalLabel
  const checkNotificationsForShow: typeof import('../composables/notification.js').checkNotificationsForShow
  const checkSentinel: typeof import('../utils/core').checkSentinel
  const clampDecimals: typeof import('../utils/amount').clampDecimals
  const collectRestoreErrors: typeof import('../utils/full-backup-helpers').collectRestoreErrors
  const comma: typeof import('../utils/amount').comma
  const completeImportWithRecovery: typeof import('../composables/completeImportWithRecovery').completeImportWithRecovery
  const compressData: typeof import('../utils/files').compressData
  const computeMaxFee: typeof import('../utils/fee-estimation').computeMaxFee
  const computed: typeof import('vue').computed
  const confirmationPolicies: typeof import('../utils/confirmation-policies').confirmationPolicies
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const debounce: typeof import('../utils/general').debounce
  const decompressData: typeof import('../utils/files').decompressData
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const detectBackupType: typeof import('../utils/full-backup-helpers').detectBackupType
  const downloadFile: typeof import('../utils/files').downloadFile
  const effectScope: typeof import('vue').effectScope
  const feeJuicePricingFromUsd: typeof import('../utils/fee-estimation').feeJuicePricingFromUsd
  const feeToUsd: typeof import('../utils/fee-estimation').feeToUsd
  const formatBaseUnits: typeof import('../utils/amount').formatBaseUnits
  const formatCallSummary: typeof import('../utils/tx-enrichment').formatCallSummary
  const formatFeeJuice: typeof import('../utils/fee-estimation').formatFeeJuice
  const formatGas: typeof import('../utils/fee-estimation').formatGas
  const formatTransferType: typeof import('../utils/tx-enrichment').formatTransferType
  const getAccount: typeof import('../utils/core').getAccount
  const getCallCountLabel: typeof import('../utils/tx-enrichment').getCallCountLabel
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getDecimalSeparator: typeof import('../utils/amount').getDecimalSeparator
  const getInitials: typeof import('../utils/string').getInitials
  const getLastActiveProfileId: typeof import('../utils/lastActiveProfile').getLastActiveProfileId
  const getMethodLabel: typeof import('../utils/tx-enrichment').getMethodLabel
  const getNetwork: typeof import('../utils/core').getNetwork
  const getOriginLabel: typeof import('../utils/tx-enrichment').getOriginLabel
  const getPrimaryCall: typeof import('../utils/tx-enrichment').getPrimaryCall
  const getTemplate: typeof import('../composables/notification.js').getTemplate
  const getThousandSeparator: typeof import('../utils/amount').getThousandSeparator
  const getTransaction: typeof import('../utils/core').getTransaction
  const getTxCategory: typeof import('../utils/tx-enrichment').getTxCategory
  const getTxTitle: typeof import('../utils/tx-enrichment').getTxTitle
  const h: typeof import('vue').h
  const hasInFlightSend: typeof import('../utils/in-flight-send').hasInFlightSend
  const humanizeErrorKind: typeof import('../utils/journal-state').humanizeErrorKind
  const humanizeMethodName: typeof import('../utils/tx-enrichment').humanizeMethodName
  const initAppServiceContext: typeof import('../utils/core').initAppServiceContext
  const initTransactionService: typeof import('../utils/core').initTransactionService
  const inject: typeof import('vue').inject
  const isBackgroundConnected: typeof import('../utils/core').isBackgroundConnected
  const isInFlightSend: typeof import('../utils/in-flight-send').isInFlightSend
  const isPrefersDarkScheme: typeof import('../utils/general').isPrefersDarkScheme
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isReceiptAboveDustThreshold: typeof import('../utils/incoming-dust').isReceiptAboveDustThreshold
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const isValidAmount: typeof import('../utils/amount').isValidAmount
  const isValidHex: typeof import('../utils/string').isValidHex
  const journalTerminalDisplay: typeof import('../utils/journal-state').journalTerminalDisplay
  const managers: typeof import('../utils/core').managers
  const markRaw: typeof import('vue').markRaw
  const migrationIdle: typeof import('../utils/storage').migrationIdle
  const nextTick: typeof import('vue').nextTick
  const normalizeAllIds: typeof import('../utils/full-backup-helpers').normalizeAllIds
  const normalizeAmount: typeof import('../utils/amount').normalizeAmount
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const parseAmountToBaseUnits: typeof import('../utils/amount').parseAmountToBaseUnits
  const parseContactsExport: typeof import('../utils/contacts-export-format').parseContactsExport
  const parseTransferIntent: typeof import('../utils/transfer-intent').parseTransferIntent
  const persistThemeHint: typeof import('../utils/general').persistThemeHint
  const pickFile: typeof import('../utils/files').pickFile
  const pickPrimaryIndex: typeof import('../utils/primary-method').pickPrimaryIndex
  const pickPrimaryMethod: typeof import('../utils/tx-enrichment').pickPrimaryMethod
  const provide: typeof import('vue').provide
  const purgeNumber: typeof import('../utils/amount').purgeNumber
  const reactive: typeof import('vue').reactive
  const readBackupFile: typeof import('../utils/full-backup-helpers').readBackupFile
  const readonly: typeof import('vue').readonly
  const receivedLabel: typeof import('../utils/received-display').receivedLabel
  const ref: typeof import('vue').ref
  const refreshBalances: typeof import('../utils/core').refreshBalances
  const remapByMap: typeof import('../utils/full-backup-helpers').remapByMap
  const requireAccount: typeof import('../utils/core').requireAccount
  const requireNetwork: typeof import('../utils/core').requireNetwork
  const requireTransaction: typeof import('../utils/core').requireTransaction
  const resolveComponent: typeof import('vue').resolveComponent
  const resolveFromDisplay: typeof import('../utils/received-display').resolveFromDisplay
  const resolveReceivedType: typeof import('../utils/received-display').resolveReceivedType
  const resolveRestoredActiveNetworkId: typeof import('../utils/full-backup-helpers').resolveRestoredActiveNetworkId
  const sanitizeJournalSubtitle: typeof import('../utils/journal-state').sanitizeJournalSubtitle
  const sanitizeString: typeof import('../utils/string').sanitizeString
  const setLastActiveProfileId: typeof import('../utils/lastActiveProfile').setLastActiveProfileId
  const setSentinel: typeof import('../utils/core').setSentinel
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const stageSubtitle: typeof import('../utils/card-subtitle').stageSubtitle
  const storageLocalGet: typeof import('../utils/storage').storageLocalGet
  const storageLocalRemove: typeof import('../utils/storage').storageLocalRemove
  const storageLocalSet: typeof import('../utils/storage').storageLocalSet
  const stringCompare: typeof import('../utils/string').stringCompare
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toRestoreError: typeof import('../utils/restore-error').toRestoreError
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const trimAddress: typeof import('../utils/string').trimAddress
  const txBelongsToScope: typeof import('../stores/activity.store').txBelongsToScope
  const txScope: typeof import('../stores/activity.store').txScope
  const unref: typeof import('vue').unref
  const usdThresholdToMicro: typeof import('../utils/incoming-dust').usdThresholdToMicro
  const useAcceleratorStatus: typeof import('../onboarding/composables/useAcceleratorStatus').useAcceleratorStatus
  const useActivityStore: typeof import('../stores/activity.store').useActivityStore
  const useAppStore: typeof import('../stores/app.store').useAppStore
  const useAttrs: typeof import('vue').useAttrs
  const useCacheStore: typeof import('../stores/cache.store').useCacheStore
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDappApprovalWindow: typeof import('../composables/useDappApprovalWindow').useDappApprovalWindow
  const useDappHostname: typeof import('../composables/useDappHostname').useDappHostname
  const useDappInteractionPayload: typeof import('../composables/useDappInteractionPayload').useDappInteractionPayload
  const useEntityCrud: typeof import('../composables/useEntityCrud').useEntityCrud
  const useEvent: typeof import('../composables/outside.js').useEvent
  const useFeeEstimation: typeof import('../composables/useFeeEstimation').useFeeEstimation
  const useFeeEstimationMap: typeof import('../composables/useFeeEstimationMap').useFeeEstimationMap
  const useFormState: typeof import('../composables/useFormState').useFormState
  const useFullBackupImport: typeof import('../composables/useFullBackupImport').useFullBackupImport
  const useFullscreenPopupSetting: typeof import('../composables/fullscreenPopupSetting').useFullscreenPopupSetting
  const useId: typeof import('vue').useId
  const useInFlightSend: typeof import('../composables/useInFlightSend').useInFlightSend
  const useIncomingTransfers: typeof import('../composables/useIncomingTransfers').useIncomingTransfers
  const useLink: typeof import('vue-router').useLink
  const useModel: typeof import('vue').useModel
  const useNotificationStore: typeof import('../stores/notification.store').useNotificationStore
  const useOutside: typeof import('../composables/outside.js').useOutside
  const usePasskeyCeremony: typeof import('../composables/usePasskeyCeremony').usePasskeyCeremony
  const usePopupEntity: typeof import('../composables/usePopupEntity').usePopupEntity
  const usePopupStore: typeof import('../stores/popup.store').usePopupStore
  const usePrices: typeof import('../composables/usePrices').usePrices
  const useProfileBootstrap: typeof import('../composables/useProfileBootstrap').useProfileBootstrap
  const useProfileCreateFlow: typeof import('../composables/useProfileCreateFlow').useProfileCreateFlow
  const useProfileImportFlow: typeof import('../composables/useProfileImportFlow').useProfileImportFlow
  const useProfileNameField: typeof import('../composables/useProfileNameField').useProfileNameField
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSecretCountdown: typeof import('../composables/useSecretCountdown').useSecretCountdown
  const useSlots: typeof import('vue').useSlots
  const useSyncedRef: typeof import('../composables/syncedRef.js').useSyncedRef
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTicker: typeof import('../composables/ticker').useTicker
  const useToast: typeof import('../composables/toast.js').useToast
  const userMethodsOf: typeof import('../utils/primary-method').userMethodsOf
  const waitForProfileActive: typeof import('../composables/waitForProfileActive').waitForProfileActive
  const walletChainId: typeof import('../utils/chain-ids').walletChainId
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ImportCompletionDeps, ImportCompletionOutcome } from '../composables/completeImportWithRecovery'
  import('../composables/completeImportWithRecovery')
  // @ts-ignore
  export type { DappWindowError, UseDappApprovalWindowOptions, UseDappApprovalWindowResult } from '../composables/useDappApprovalWindow'
  import('../composables/useDappApprovalWindow')
  // @ts-ignore
  export type { UIDappMetadata, DappInteractionLike, UseDappInteractionPayloadOptions, UseDappInteractionPayloadResult } from '../composables/useDappInteractionPayload'
  import('../composables/useDappInteractionPayload')
  // @ts-ignore
  export type { EntityCrudMode, UseEntityCrudOptions, UseEntityCrudResult } from '../composables/useEntityCrud'
  import('../composables/useEntityCrud')
  // @ts-ignore
  export type { UseFeeEstimationOptions, UseFeeEstimationResult } from '../composables/useFeeEstimation'
  import('../composables/useFeeEstimation')
  // @ts-ignore
  export type { UseFeeEstimationMapOptions, UseFeeEstimationMapResult } from '../composables/useFeeEstimationMap'
  import('../composables/useFeeEstimationMap')
  // @ts-ignore
  export type { FieldDef, FieldHandle, FormState } from '../composables/useFormState'
  import('../composables/useFormState')
  // @ts-ignore
  export type { RestoreStatus, UseFullBackupImportOptions, UseFullBackupImportResult } from '../composables/useFullBackupImport'
  import('../composables/useFullBackupImport')
  // @ts-ignore
  export type { IncomingTransferServiceLike, ConfigServiceLike, PriceServiceLike, UseIncomingTransfersOptions, UseIncomingTransfersResult } from '../composables/useIncomingTransfers'
  import('../composables/useIncomingTransfers')
  // @ts-ignore
  export type { UsePopupEntityHandlers } from '../composables/usePopupEntity'
  import('../composables/usePopupEntity')
  // @ts-ignore
  export type { UseProfileCreateFlowOptions } from '../composables/useProfileCreateFlow'
  import('../composables/useProfileCreateFlow')
  // @ts-ignore
  export type { UseProfileImportFlowOptions } from '../composables/useProfileImportFlow'
  import('../composables/useProfileImportFlow')
  // @ts-ignore
  export type { ProfileNameFieldOptions, ValidateOptions, ProfileNameField } from '../composables/useProfileNameField'
  import('../composables/useProfileNameField')
  // @ts-ignore
  export type { UseSecretCountdownOptions } from '../composables/useSecretCountdown'
  import('../composables/useSecretCountdown')
  // @ts-ignore
  export type { ProfileActivationSubject } from '../composables/waitForProfileActive'
  import('../composables/waitForProfileActive')
  // @ts-ignore
  export type { AwaitingTx, ActivitySlice } from '../stores/activity.store'
  import('../stores/activity.store')
  // @ts-ignore
  export type { NotificationType, NotificationPayload, NotificationItem } from '../stores/notification.store'
  import('../stores/notification.store')
  // @ts-ignore
  export type { ActivityRowTx, ActivityRowJournal, ActivityRowIncoming, ActivityRow, BuildActivityRowsParams } from '../utils/activity-rows'
  import('../utils/activity-rows')
  // @ts-ignore
  export type { FormatBaseUnitsOpts } from '../utils/amount'
  import('../utils/amount')
  // @ts-ignore
  export type { ConfirmationPolicy } from '../utils/confirmation-policies'
  import('../utils/confirmation-policies')
  // @ts-ignore
  export type { ImportedContactV1, ImportedContactV2, ParsedExport } from '../utils/contacts-export-format'
  import('../utils/contacts-export-format')
  // @ts-ignore
  export type { AppServices } from '../utils/core'
  import('../utils/core')
  // @ts-ignore
  export type { AssetPricing, FeeEstimate } from '../utils/fee-estimation'
  import('../utils/fee-estimation')
  // @ts-ignore
  export type { BackupFileType, BackupSelection, ProcessBackupResult } from '../utils/full-backup-helpers'
  import('../utils/full-backup-helpers')
  // @ts-ignore
  export type { NetworkActivationResult } from '../utils/guarded-network-activation'
  import('../utils/guarded-network-activation')
  // @ts-ignore
  export type { InFlightScope } from '../utils/in-flight-send'
  import('../utils/in-flight-send')
  // @ts-ignore
  export type { JournalTerminalVisualState, JournalTerminalDisplay, CategoricalFailureLabel, TokenForCardProps, JournalTerminalCardCtx, JournalTerminalCardProps } from '../utils/journal-state'
  import('../utils/journal-state')
  // @ts-ignore
  export type { MethodCarrier } from '../utils/primary-method'
  import('../utils/primary-method')
  // @ts-ignore
  export type { ReceivedType, FromDisplay } from '../utils/received-display'
  import('../utils/received-display')
  // @ts-ignore
  export type { TransferIntent } from '../utils/transfer-intent'
  import('../utils/transfer-intent')
  // @ts-ignore
  export type { AcceleratorStatus } from '../onboarding/composables/useAcceleratorStatus'
  import('../onboarding/composables/useAcceleratorStatus')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly ACTIVITY_FEED_KINDS: UnwrapRef<typeof import('../utils/journal-state')['ACTIVITY_FEED_KINDS']>
    readonly AccessLevel: UnwrapRef<typeof import('../utils/confirmation-policies')['AccessLevel']>
    readonly CHAIN_IDS: UnwrapRef<typeof import('../utils/chain-ids')['CHAIN_IDS']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly FEE_METHODS: UnwrapRef<typeof import('../utils/tx-enrichment')['FEE_METHODS']>
    readonly IMPORT_ACTIVATION_TIMEOUT_MS: UnwrapRef<typeof import('../composables/completeImportWithRecovery')['IMPORT_ACTIVATION_TIMEOUT_MS']>
    readonly MAINNET_L1_CHAIN_ID: UnwrapRef<typeof import('../utils/chain-ids')['MAINNET_L1_CHAIN_ID']>
    readonly MAINNET_ROLLUP_VERSION: UnwrapRef<typeof import('../utils/chain-ids')['MAINNET_ROLLUP_VERSION']>
    readonly MAX_CONTACT_IMPORT_BYTES: UnwrapRef<typeof import('../utils/contacts-export-format')['MAX_CONTACT_IMPORT_BYTES']>
    readonly MAX_CONTACT_IMPORT_ROWS: UnwrapRef<typeof import('../utils/contacts-export-format')['MAX_CONTACT_IMPORT_ROWS']>
    readonly THEME_HINT_KEY: UnwrapRef<typeof import('../utils/general')['THEME_HINT_KEY']>
    readonly TOAST_DURATION: UnwrapRef<typeof import('../composables/toast.js')['TOAST_DURATION']>
    readonly activateNetworkGuarded: UnwrapRef<typeof import('../utils/guarded-network-activation')['activateNetworkGuarded']>
    readonly balanceFormatted: UnwrapRef<typeof import('../utils/amount')['balanceFormatted']>
    readonly browser: UnwrapRef<typeof import('webextension-polyfill')>
    readonly buildActivityRows: UnwrapRef<typeof import('../utils/activity-rows')['buildActivityRows']>
    readonly buildFeeEstimate: UnwrapRef<typeof import('../utils/fee-estimation')['buildFeeEstimate']>
    readonly buildJournalTerminalCardProps: UnwrapRef<typeof import('../utils/journal-state')['buildJournalTerminalCardProps']>
    readonly capitalize: UnwrapRef<typeof import('../utils/string')['capitalize']>
    readonly categoricalLabel: UnwrapRef<typeof import('../utils/journal-state')['categoricalLabel']>
    readonly checkNotificationsForShow: UnwrapRef<typeof import('../composables/notification.js')['checkNotificationsForShow']>
    readonly checkSentinel: UnwrapRef<typeof import('../utils/core')['checkSentinel']>
    readonly clampDecimals: UnwrapRef<typeof import('../utils/amount')['clampDecimals']>
    readonly collectRestoreErrors: UnwrapRef<typeof import('../utils/full-backup-helpers')['collectRestoreErrors']>
    readonly comma: UnwrapRef<typeof import('../utils/amount')['comma']>
    readonly completeImportWithRecovery: UnwrapRef<typeof import('../composables/completeImportWithRecovery')['completeImportWithRecovery']>
    readonly compressData: UnwrapRef<typeof import('../utils/files')['compressData']>
    readonly computeMaxFee: UnwrapRef<typeof import('../utils/fee-estimation')['computeMaxFee']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly confirmationPolicies: UnwrapRef<typeof import('../utils/confirmation-policies')['confirmationPolicies']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly debounce: UnwrapRef<typeof import('../utils/general')['debounce']>
    readonly decompressData: UnwrapRef<typeof import('../utils/files')['decompressData']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly detectBackupType: UnwrapRef<typeof import('../utils/full-backup-helpers')['detectBackupType']>
    readonly downloadFile: UnwrapRef<typeof import('../utils/files')['downloadFile']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly feeJuicePricingFromUsd: UnwrapRef<typeof import('../utils/fee-estimation')['feeJuicePricingFromUsd']>
    readonly feeToUsd: UnwrapRef<typeof import('../utils/fee-estimation')['feeToUsd']>
    readonly formatBaseUnits: UnwrapRef<typeof import('../utils/amount')['formatBaseUnits']>
    readonly formatCallSummary: UnwrapRef<typeof import('../utils/tx-enrichment')['formatCallSummary']>
    readonly formatFeeJuice: UnwrapRef<typeof import('../utils/fee-estimation')['formatFeeJuice']>
    readonly formatGas: UnwrapRef<typeof import('../utils/fee-estimation')['formatGas']>
    readonly formatTransferType: UnwrapRef<typeof import('../utils/tx-enrichment')['formatTransferType']>
    readonly getAccount: UnwrapRef<typeof import('../utils/core')['getAccount']>
    readonly getCallCountLabel: UnwrapRef<typeof import('../utils/tx-enrichment')['getCallCountLabel']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getDecimalSeparator: UnwrapRef<typeof import('../utils/amount')['getDecimalSeparator']>
    readonly getInitials: UnwrapRef<typeof import('../utils/string')['getInitials']>
    readonly getLastActiveProfileId: UnwrapRef<typeof import('../utils/lastActiveProfile')['getLastActiveProfileId']>
    readonly getMethodLabel: UnwrapRef<typeof import('../utils/tx-enrichment')['getMethodLabel']>
    readonly getNetwork: UnwrapRef<typeof import('../utils/core')['getNetwork']>
    readonly getOriginLabel: UnwrapRef<typeof import('../utils/tx-enrichment')['getOriginLabel']>
    readonly getPrimaryCall: UnwrapRef<typeof import('../utils/tx-enrichment')['getPrimaryCall']>
    readonly getTemplate: UnwrapRef<typeof import('../composables/notification.js')['getTemplate']>
    readonly getThousandSeparator: UnwrapRef<typeof import('../utils/amount')['getThousandSeparator']>
    readonly getTransaction: UnwrapRef<typeof import('../utils/core')['getTransaction']>
    readonly getTxCategory: UnwrapRef<typeof import('../utils/tx-enrichment')['getTxCategory']>
    readonly getTxTitle: UnwrapRef<typeof import('../utils/tx-enrichment')['getTxTitle']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly hasInFlightSend: UnwrapRef<typeof import('../utils/in-flight-send')['hasInFlightSend']>
    readonly humanizeErrorKind: UnwrapRef<typeof import('../utils/journal-state')['humanizeErrorKind']>
    readonly humanizeMethodName: UnwrapRef<typeof import('../utils/tx-enrichment')['humanizeMethodName']>
    readonly initAppServiceContext: UnwrapRef<typeof import('../utils/core')['initAppServiceContext']>
    readonly initTransactionService: UnwrapRef<typeof import('../utils/core')['initTransactionService']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isBackgroundConnected: UnwrapRef<typeof import('../utils/core')['isBackgroundConnected']>
    readonly isInFlightSend: UnwrapRef<typeof import('../utils/in-flight-send')['isInFlightSend']>
    readonly isPrefersDarkScheme: UnwrapRef<typeof import('../utils/general')['isPrefersDarkScheme']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isReceiptAboveDustThreshold: UnwrapRef<typeof import('../utils/incoming-dust')['isReceiptAboveDustThreshold']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly isValidAmount: UnwrapRef<typeof import('../utils/amount')['isValidAmount']>
    readonly isValidHex: UnwrapRef<typeof import('../utils/string')['isValidHex']>
    readonly journalTerminalDisplay: UnwrapRef<typeof import('../utils/journal-state')['journalTerminalDisplay']>
    readonly managers: UnwrapRef<typeof import('../utils/core')['managers']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly migrationIdle: UnwrapRef<typeof import('../utils/storage')['migrationIdle']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly normalizeAllIds: UnwrapRef<typeof import('../utils/full-backup-helpers')['normalizeAllIds']>
    readonly normalizeAmount: UnwrapRef<typeof import('../utils/amount')['normalizeAmount']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly parseAmountToBaseUnits: UnwrapRef<typeof import('../utils/amount')['parseAmountToBaseUnits']>
    readonly parseContactsExport: UnwrapRef<typeof import('../utils/contacts-export-format')['parseContactsExport']>
    readonly parseTransferIntent: UnwrapRef<typeof import('../utils/transfer-intent')['parseTransferIntent']>
    readonly persistThemeHint: UnwrapRef<typeof import('../utils/general')['persistThemeHint']>
    readonly pickFile: UnwrapRef<typeof import('../utils/files')['pickFile']>
    readonly pickPrimaryIndex: UnwrapRef<typeof import('../utils/primary-method')['pickPrimaryIndex']>
    readonly pickPrimaryMethod: UnwrapRef<typeof import('../utils/tx-enrichment')['pickPrimaryMethod']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly purgeNumber: UnwrapRef<typeof import('../utils/amount')['purgeNumber']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readBackupFile: UnwrapRef<typeof import('../utils/full-backup-helpers')['readBackupFile']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly receivedLabel: UnwrapRef<typeof import('../utils/received-display')['receivedLabel']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly refreshBalances: UnwrapRef<typeof import('../utils/core')['refreshBalances']>
    readonly remapByMap: UnwrapRef<typeof import('../utils/full-backup-helpers')['remapByMap']>
    readonly requireAccount: UnwrapRef<typeof import('../utils/core')['requireAccount']>
    readonly requireNetwork: UnwrapRef<typeof import('../utils/core')['requireNetwork']>
    readonly requireTransaction: UnwrapRef<typeof import('../utils/core')['requireTransaction']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly resolveFromDisplay: UnwrapRef<typeof import('../utils/received-display')['resolveFromDisplay']>
    readonly resolveReceivedType: UnwrapRef<typeof import('../utils/received-display')['resolveReceivedType']>
    readonly resolveRestoredActiveNetworkId: UnwrapRef<typeof import('../utils/full-backup-helpers')['resolveRestoredActiveNetworkId']>
    readonly sanitizeJournalSubtitle: UnwrapRef<typeof import('../utils/journal-state')['sanitizeJournalSubtitle']>
    readonly sanitizeString: UnwrapRef<typeof import('../utils/string')['sanitizeString']>
    readonly setLastActiveProfileId: UnwrapRef<typeof import('../utils/lastActiveProfile')['setLastActiveProfileId']>
    readonly setSentinel: UnwrapRef<typeof import('../utils/core')['setSentinel']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly stageSubtitle: UnwrapRef<typeof import('../utils/card-subtitle')['stageSubtitle']>
    readonly storageLocalGet: UnwrapRef<typeof import('../utils/storage')['storageLocalGet']>
    readonly storageLocalRemove: UnwrapRef<typeof import('../utils/storage')['storageLocalRemove']>
    readonly storageLocalSet: UnwrapRef<typeof import('../utils/storage')['storageLocalSet']>
    readonly stringCompare: UnwrapRef<typeof import('../utils/string')['stringCompare']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toRestoreError: UnwrapRef<typeof import('../utils/restore-error')['toRestoreError']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly trimAddress: UnwrapRef<typeof import('../utils/string')['trimAddress']>
    readonly txBelongsToScope: UnwrapRef<typeof import('../stores/activity.store')['txBelongsToScope']>
    readonly txScope: UnwrapRef<typeof import('../stores/activity.store')['txScope']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly usdThresholdToMicro: UnwrapRef<typeof import('../utils/incoming-dust')['usdThresholdToMicro']>
    readonly useAcceleratorStatus: UnwrapRef<typeof import('../onboarding/composables/useAcceleratorStatus')['useAcceleratorStatus']>
    readonly useActivityStore: UnwrapRef<typeof import('../stores/activity.store')['useActivityStore']>
    readonly useAppStore: UnwrapRef<typeof import('../stores/app.store')['useAppStore']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCacheStore: UnwrapRef<typeof import('../stores/cache.store')['useCacheStore']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDappApprovalWindow: UnwrapRef<typeof import('../composables/useDappApprovalWindow')['useDappApprovalWindow']>
    readonly useDappHostname: UnwrapRef<typeof import('../composables/useDappHostname')['useDappHostname']>
    readonly useDappInteractionPayload: UnwrapRef<typeof import('../composables/useDappInteractionPayload')['useDappInteractionPayload']>
    readonly useEntityCrud: UnwrapRef<typeof import('../composables/useEntityCrud')['useEntityCrud']>
    readonly useEvent: UnwrapRef<typeof import('../composables/outside.js')['useEvent']>
    readonly useFeeEstimation: UnwrapRef<typeof import('../composables/useFeeEstimation')['useFeeEstimation']>
    readonly useFeeEstimationMap: UnwrapRef<typeof import('../composables/useFeeEstimationMap')['useFeeEstimationMap']>
    readonly useFormState: UnwrapRef<typeof import('../composables/useFormState')['useFormState']>
    readonly useFullBackupImport: UnwrapRef<typeof import('../composables/useFullBackupImport')['useFullBackupImport']>
    readonly useFullscreenPopupSetting: UnwrapRef<typeof import('../composables/fullscreenPopupSetting')['useFullscreenPopupSetting']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useIncomingTransfers: UnwrapRef<typeof import('../composables/useIncomingTransfers')['useIncomingTransfers']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNotificationStore: UnwrapRef<typeof import('../stores/notification.store')['useNotificationStore']>
    readonly useOutside: UnwrapRef<typeof import('../composables/outside.js')['useOutside']>
    readonly usePasskeyCeremony: UnwrapRef<typeof import('../composables/usePasskeyCeremony')['usePasskeyCeremony']>
    readonly usePopupEntity: UnwrapRef<typeof import('../composables/usePopupEntity')['usePopupEntity']>
    readonly usePopupStore: UnwrapRef<typeof import('../stores/popup.store')['usePopupStore']>
    readonly usePrices: UnwrapRef<typeof import('../composables/usePrices')['usePrices']>
    readonly useProfileBootstrap: UnwrapRef<typeof import('../composables/useProfileBootstrap')['useProfileBootstrap']>
    readonly useProfileCreateFlow: UnwrapRef<typeof import('../composables/useProfileCreateFlow')['useProfileCreateFlow']>
    readonly useProfileImportFlow: UnwrapRef<typeof import('../composables/useProfileImportFlow')['useProfileImportFlow']>
    readonly useProfileNameField: UnwrapRef<typeof import('../composables/useProfileNameField')['useProfileNameField']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSecretCountdown: UnwrapRef<typeof import('../composables/useSecretCountdown')['useSecretCountdown']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useSyncedRef: UnwrapRef<typeof import('../composables/syncedRef.js')['useSyncedRef']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useTicker: UnwrapRef<typeof import('../composables/ticker')['useTicker']>
    readonly useToast: UnwrapRef<typeof import('../composables/toast.js')['useToast']>
    readonly userMethodsOf: UnwrapRef<typeof import('../utils/primary-method')['userMethodsOf']>
    readonly waitForProfileActive: UnwrapRef<typeof import('../composables/waitForProfileActive')['waitForProfileActive']>
    readonly walletChainId: UnwrapRef<typeof import('../utils/chain-ids')['walletChainId']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}