/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressDisplay: typeof import('./../components/AddressDisplay.vue')['default']
    AmountCard: typeof import('./../components/composite/send/AmountCard.vue')['default']
    Badge: typeof import('./../components/ui/Badge.vue')['default']
    Banner: typeof import('./../components/ui/Banner.vue')['default']
    Button: typeof import('./../components/ui/Button.vue')['default']
    CapabilityDetailPanel: typeof import('./../components/composite/capabilities/CapabilityDetailPanel.vue')['default']
    Checkbox: typeof import('./../components/ui/Checkbox.vue')['default']
    DappCancelledOverlay: typeof import('./../components/composite/DappCancelledOverlay.vue')['default']
    DappIdentityBlock: typeof import('./../components/composite/DappIdentityBlock.vue')['default']
    DappStatusStrip: typeof import('./../components/composite/DappStatusStrip.vue')['default']
    Divider: typeof import('./../components/Divider.vue')['default']
    DropdownDivider: typeof import('./../components/ui/Dropdown/DropdownDivider.vue')['default']
    DropdownItem: typeof import('./../components/ui/Dropdown/DropdownItem.vue')['default']
    DropdownRoot: typeof import('./../components/ui/Dropdown/DropdownRoot.vue')['default']
    DropdownTitle: typeof import('./../components/ui/Dropdown/DropdownTitle.vue')['default']
    DropdownTrigger: typeof import('./../components/ui/Dropdown/DropdownTrigger.vue')['default']
    EmojiGrid: typeof import('./../components/composite/general/EmojiGrid.vue')['default']
    FeeJuiceCard: typeof import('./../components/composite/send/FeeJuiceCard.vue')['default']
    Flex: typeof import('./../components/core/Flex.vue')['default']
    FormPopup: typeof import('./../components/composite/FormPopup.vue')['default']
    GlobalLoader: typeof import('./../components/GlobalLoader.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    Icon: typeof import('./../components/core/Icon.vue')['default']
    ImportFullBackupForm: typeof import('./../components/composite/import/ImportFullBackupForm.vue')['default']
    ImportMethodPicker: typeof import('./../components/composite/import/ImportMethodPicker.vue')['default']
    ImportSecretForm: typeof import('./../components/composite/import/ImportSecretForm.vue')['default']
    Input: typeof import('./../components/ui/Input.vue')['default']
    Install: typeof import('./../components/install.vue')['default']
    ItemsContainer: typeof import('./../components/ui/Settings/ItemsContainer.vue')['default']
    JsonViewer: typeof import('./../components/JsonViewer/JsonViewer.vue')['default']
    LoadingState: typeof import('./../components/ui/LoadingState.vue')['default']
    LogsToolbar: typeof import('./../components/JsonViewer/LogsToolbar.vue')['default']
    LogsViewer: typeof import('./../components/JsonViewer/LogsViewer.vue')['default']
    MaterialIcon: typeof import('./../components/core/MaterialIcon.vue')['default']
    NotificationManager: typeof import('./../components/NotificationManager.vue')['default']
    Popover: typeof import('./../components/ui/Popover.vue')['default']
    Popup: typeof import('./../components/Popup/Popup.vue')['default']
    PopupCard: typeof import('./../components/Popup/PopupCard.vue')['default']
    PopupHeader: typeof import('./../components/ui/Popup/PopupHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecretCountdownClose: typeof import('./../components/composite/SecretCountdownClose.vue')['default']
    SecretExportLayout: typeof import('./../components/composite/SecretExportLayout.vue')['default']
    SecretRevealCard: typeof import('./../components/composite/SecretRevealCard.vue')['default']
    SecretUnlockSection: typeof import('./../components/composite/SecretUnlockSection.vue')['default']
    SectionLabel: typeof import('./../components/ui/SectionLabel.vue')['default']
    SendTypesCard: typeof import('./../components/composite/send/SendTypesCard.vue')['default']
    SettingField: typeof import('./../components/ui/Settings/SettingField.vue')['default']
    SettingItem: typeof import('./../components/ui/Settings/SettingItem.vue')['default']
    SettingValue: typeof import('./../components/ui/Settings/SettingValue.vue')['default']
    Spinner: typeof import('./../components/ui/Spinner.vue')['default']
    SubPageHeader: typeof import('./../components/ui/SubPageHeader.vue')['default']
    Text: typeof import('./../components/core/Text.vue')['default']
    ToastManager: typeof import('./../components/ui/ToastManager.vue')['default']
    Toggle: typeof import('./../components/ui/Toggle.vue')['default']
    Tooltip: typeof import('./../components/ui/Tooltip.vue')['default']
    TransactionAwaitingCard: typeof import('./../components/composite/activity/TransactionAwaitingCard.vue')['default']
    TransactionCardLayout: typeof import('./../components/composite/activity/TransactionCardLayout.vue')['default']
    TransactionTerminalCard: typeof import('./../components/composite/activity/TransactionTerminalCard.vue')['default']
    Update: typeof import('./../components/update.vue')['default']
  }
}
