import { afterAll, describe, expect, test } from "bun:test"
import { baseIndexLines, closedTargets, indexView, readClosures } from "./closed"
import { cleanupRepos, closuresRepo, commitAll, git, memView, P, planTree, read, row, tool, writeFiles } from "./fixture"
import { followUpEntries, isSeed, openItems, outcomeProblems, planOutcomes, untouchedProblems } from "./outcome"

afterAll(cleanupRepos)

const SEEDS =
	"- **Seeds retired**: the `/goal` and `/loop` seeds in this directory are spent and must never be pasted. Generated by plans-scaffolding on 2026-09-30."
const LINE = "> Seeds retired (2026-09-30): the `/goal` and `/loop` seeds in this file are spent and must never be pasted."
const block = (date: string, status: string, shipped: string, open: string) =>
	[
		"## Outcome",
		"",
		`- **Date**: ${date}. **Status**: ${status}.`,
		`- **Shipped**: ${shipped}.`,
		`- **Open items**: ${open}.`,
		SEEDS,
	].join("\n")

function targetsOf(repo: string) {
	const closures = readClosures(repo)
	return closedTargets(indexView(repo), closures, baseIndexLines(repo, closures))
}

describe("outcome", () => {
	test("a seed block is a rendered code block whose text starts /goal or /loop, then a space or its end", () => {
		expect(["/goal ship", "\n  /loop 5m", "/goal"].every(isSeed)).toBe(true)
		expect(["/goals x", "paste /goal x", "goal x", "/looping"].some(isSeed)).toBe(false)
	})

	test("writes every closed block where A15 puts it, completes a partial one inside it, retires seeds, and leaves live dirs alone", () => {
		const { files, rows } = planTree()
		const { repo, head } = closuresRepo(files, rows)
		const run = tool(repo, "outcome", "--date", "2026-09-30")
		expect(run.out).toContain("block=5 fields=1 stub=1 nested=1 seed=3")
		const at = (path: string) => read(repo, `${P}/${path}`)
		const was = (path: string) => files[`${P}/${path}`]
		expect(at("done/plan.md")).toBe(
			`${block("2026-09-01", "completed", "#5, #6", 'follow-ups.md "Fix the thing"')}\n\n${was("done/plan.md")}`,
		)
		const historical = block("2026-05-19", "historical — pre-open-source import (2026-05-19)", "no PR recorded", "none")
		expect(at("fm/plan.md")).toBe(was("fm/plan.md").replace("---\n\n# FM", `---\n\n${historical}\n\n# FM`))
		expect(at("partial/plan.md")).toBe(was("partial/plan.md").replace("spent.\n", "spent.\n- **Shipped**: #7.\n"))
		const child = block(
			"2026-09-01",
			"closed with parent nest (completed)",
			"#8 (recorded for nest)",
			`follow-ups.md "A child's loose end"`,
		)
		expect(at("nest/child/plan.md")).toBe(`${child}\n\n${was("nest/child/plan.md")}`)
		expect(at("stubbed/plan.md")).toBe(
			`${block("2026-09-01", "completed", "no PR recorded", "none")}\n\n# stubbed\n\nThis directory kept no plan of record, so this stub carries its Outcome. Its files: [notes.md](notes.md).\n`,
		)
		expect(at("seeds/goal.md")).toBe(was("seeds/goal.md").replace("Paste:\n\n", `Paste:\n\n${LINE}\n\n`))
		expect(at("seeds/indented.md")).toBe(was("seeds/indented.md").replace("# Indented\n\n", `# Indented\n\n${LINE}\n\n`))
		expect(at("seeds/eli5-v2.html")).toBe(
			was("seeds/eli5-v2.html").replace(
				"<pre>",
				"<blockquote>Seeds retired (2026-09-30): the <code>/goal</code> and <code>/loop</code> seeds in this file are spent and must never be pasted.</blockquote><pre>",
			),
		)
		for (const path of ["whole/plan.md", "live/plan.md", "parked/plan.md", "plans-scaffolding/plan.md", "stubbed/notes.md"])
			expect(at(path)).toBe(files[`${P}/${path}`])
		commitAll(repo, "outcomes")
		expect(tool(repo, "outcome", "--verify", "--parent", head).status).toBe(0)
		expect(tool(repo, "outcome", "--date", "2026-09-30").status).toBe(0)
		expect(git(repo, "status", "--short")).toBe("")
	})

	test("refuses, writing nothing, while an index line newer than the table leaves a closed dir open", () => {
		const { files, rows } = planTree()
		const { repo } = closuresRepo(files, rows)
		const index = files[`${P}/index.md`]
		writeFiles(repo, { [`${P}/index.md`]: `${index}- [fm](fm/plan.md) — in progress — reopened\n` })
		commitAll(repo, "reopen")
		const refused = tool(repo, "outcome", "--date", "2026-09-30")
		expect(refused.status).not.toBe(0)
		expect(refused.out).toContain("fm: index.md:22 postdates the closure table and does not close it")
		expect(git(repo, "status", "--short")).toBe("")
		writeFiles(repo, { [`${P}/index.md`]: `${index}- [fm](fm/plan.md) — closed, awaiting archive — closing\n` })
		commitAll(repo, "closing")
		expect(tool(repo, "outcome", "--date", "2026-09-30").status).toBe(0)
	})

	test("verify names misplaced, partial and doubled blocks, unmined follow-ups, and a live dir whose Outcome changed", () => {
		const { repo, head } = closuresRepo(
			{
				[`${P}/index.md`]: "# Index\n",
				[`${P}/follow-ups.md`]: "# Follow-ups\n",
				[`${P}/mis/plan.md`]: "# Mis\n\n## Outcome\n\n- **Date**: d. **Status**: s.\n- **Shipped**: #1.\n- **Seeds retired**: r.\n",
				[`${P}/twice/plan.md`]: "## Outcome\n\nDate: a\n\n## Outcome\n\nb\n",
				[`${P}/half/plan.md`]: "## Outcome\n\n- **Date**: d.\n\n# Half\n",
				[`${P}/owed/plan.md`]: "# Owed\n",
				[`${P}/live/plan.md`]: "# Live\n",
			},
			[
				row("half"),
				row("live", { class: "active", status: "ACTIVE" }),
				row("mis"),
				row("owed", { followUps: ["owed-item"] }),
				row("twice"),
			],
		)
		expect(outcomeProblems(indexView(repo), targetsOf(repo), { stamp: "2026-09-30", followUps: [] })).toEqual([
			`${P}/half/plan.md: its Outcome is incomplete`,
			`${P}/mis/plan.md: its Outcome is not where A15 puts it`,
			`${P}/owed/plan.md: 0 Outcome blocks`,
			`${P}/twice/plan.md: 2 Outcome blocks`,
			"owed: closures.json names owed-item, but no follow-ups.md entry links into it",
			`${P}/twice/plan.md has 2 Outcome blocks`,
		])
		writeFiles(repo, { [`${P}/live/plan.md`]: "## Outcome\n\n- **Date**: d.\n\n# Live\n" })
		git(repo, "add", "-A")
		expect(untouchedProblems(repo, head, indexView(repo), new Set(["half", "mis", "owed", "twice"]))).toEqual([
			`${P}/live/plan.md: an Outcome or seed line changed in a dir the closure table does not close`,
		])
	})

	test("follow-up entries are named without markup and matched whether their dir sits in the plan tree or the archive", () => {
		const entries = followUpEntries(
			"- **Bold [title](x/plan.md)** — text.\n- First sentence with [a link](archive/x/notes.md). More.\n- **Other** — [y](y/plan.md).\n",
		)
		expect(openItems(entries, `${P}/x`)).toEqual(["Bold title", "First sentence with a link"])
		expect(openItems(entries, `${P}/archive/x`)).toEqual(["Bold title", "First sentence with a link"])
	})

	test("refuses, writing nothing, to overwrite a file whose working copy differs from the index", () => {
		const { files, rows } = planTree()
		const { repo } = closuresRepo(files, rows)
		writeFiles(repo, { [`${P}/fm/plan.md`]: "# Unstaged edit\n" })
		const run = tool(repo, "outcome", "--date", "2026-09-30")
		expect(run.status).not.toBe(0)
		expect(run.out).toContain(`unstaged edits in:\n  ${P}/fm/plan.md`)
		expect(git(repo, "status", "--short")).toBe(`M ${P}/fm/plan.md`)
	})

	test("a block stays within 1 KiB by counting the open items it cannot name", () => {
		const followUps = Array.from({ length: 40 }, (_, i) => ({
			name: `a long follow-up title number ${i}`,
			paths: [`${P}/big/plan.md`],
		}))
		const view = memView({ [`${P}/big/plan.md`]: "# Big\n" })
		const [edit] = planOutcomes(view, [{ row: row("big"), at: `${P}/big` }], { stamp: "2026-09-30", followUps }).values()
		const written = edit.text.slice(0, edit.text.indexOf("\n\n# Big"))
		expect(Buffer.byteLength(written)).toBeLessThanOrEqual(1024)
		expect(written).toMatch(/"a long follow-up title number 0"; .*; and \d+ more\.\n/)
	})

	test("refuses a completion that would change the page beyond the inserted fields", () => {
		const view = memView({
			[`${P}/trap/plan.md`]: "## Outcome\n\n- **Date**: d. **Status**: s.\n- **Seeds retired**: r.\n\nTwo line\nheading\n---\n",
		})
		expect(() => planOutcomes(view, [{ row: row("trap"), at: `${P}/trap` }], { stamp: "2026-09-30", followUps: [] })).toThrow(
			"cannot be written as one complete block inserted into the page",
		)
	})
})
